#!/usr/bin/env bash

trap "exit 255" ERR SIGTERM

echo "Testing gradle"

docker run -it $1 sh -c "test -x /opt/packages/gradle/gradle-2.14/bin/gradle"

echo "Testing SDK"

docker run -it $1 sh -c "test -x /usr/local/android-sdk-linux/tools/android"

 echo "Testing android 21 platform"

docker run -it $1 sh -c "test -d /usr/local/android-sdk-linux/platforms/android-21"

echo "Testing android 22 platform"

docker run -it $1 sh -c "test -d /usr/local/android-sdk-linux/platforms/android-22"

echo "Testing android 23 platform"

docker run -it $1 sh -c "test -d /usr/local/android-sdk-linux/platforms/android-23"

echo "Testing android 24 platform"

docker run -it $1 sh -c "test -d /usr/local/android-sdk-linux/platforms/android-24"

echo "Testing android 23 system image"

docker run -it $1 sh -c "test -x /usr/local/android-sdk-linux/system-images/android-23/default/armeabi-v7a/kernel-qemu"

echo "Testing android 24 system image"

docker run -it $1 sh -c "test -x /usr/local/android-sdk-linux/system-images/android-24/default/armeabi-v7a/kernel-qemu"

exit 0