#!/bin/bash

export APP_APK_PATH=$(cat Screengrabfile | grep app_apk_path | cut -d ' ' -f 2 | sed -e "s/'//g")
export TEST_APK_PATH=$(cat Screengrabfile | grep tests_apk_path | cut -d ' ' -f 2 | sed -e "s/'//g")
export PACKAGE_NAME=$(cat Screengrabfile | grep app_package_name | cut -d ' ' -f 2 | sed -e "s/'//g")

# Create AVD
echo "no" | android create avd --name test --target android-24 --sdcard 8000M --abi default/armeabi-v7a --force

# Start emulator
emulator64-arm -avd test -no-boot-anim -noaudio -no-window -gpu off &
adb wait-for-device

# Waiting for emulator to fully boot
echo 'Waiting for emulator to fully boot... (This might take several minutes)'
adb shell 'while [ ""`getprop dev.bootcomplete` != "1" ] ; do sleep 1; done'